### ISSUE TITLE
Error Fine Tuning GPT-2

### ISSUE THREAD

**Issue by adomenech73** [jungwhank/fake-review-generator#2]
Hi 

I could preprocess correctly, but unfortunately when I try to fine tune I get the following error:

```bash
Traceback (most recent call last):
  File "/Users/albert/Documents/Keybase/fake-review-generator/gpt2_fine_tuning.py", line 60, in <module>
    class TextDataset(Dataset):
  File "/Users/albert/Documents/Keybase/fake-review-generator/gpt2_fine_tuning.py", line 61, in TextDataset
    def __init__(self, tokenizer: PreTrainedTokenizer, args, file_path: str, block_size=512):
NameError: name 'PreTrainedTokenizer' is not defined
```

Seems that this step is necessary cause when I try to generate reviews seems to spect the resulting folder from previous step and I also get:

```bash
Traceback (most recent call last):
  File "/Users/albert/Documents/Keybase/fake-review-generator/gpt2_generation.py", line 188, in <module>
    main()
  File "/Users/albert/Documents/Keybase/fake-review-generator/gpt2_generation.py", line 154, in main
    tokenizer = tokenizer_class.from_pretrained(args.model_name_or_path)
  File "/Users/albert/.local/share/virtualenvs/fake-review-generator-Ph_slExn/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1708, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'positive'. Make sure that:

- 'positive' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'positive' is the correct path to a directory containing relevant tokenizer files
```

**Comment by jungwhank** [comment]
Thanks for issue and PR :)
Transformers library version has been upgraded a lot since I uploaded the repo.
I merged this, so close the issue
